name: splatoon_weapon_roulette
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  
  auto_size_text: ^2.1.0

  dotted_border: ^1.0.5

  provider: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/weapon.json
    - assets/background.png
    - assets/background_high.png
    - assets/background_none.png
    - assets/tag/tag_b.png
    - assets/tag/tag_y.png
    - assets/tag/tag_g.png
    - assets/tag/tag_p.png
    - assets/tag/tag__icon.png
    - assets/tag/tag__name.png
    - assets/tag/tag__weapon.png
    - assets/tag/tag__weaponname.png
    - assets/roulette_start.png
    - lib/Weapon/Images/sshooter.jpg
    - lib/Weapon/Images/maneuver.jpg
    - lib/Weapon/Images/splatroller.jpg
    - lib/Weapon/Images/splatcharger.jpg
    - lib/Weapon/Images/prime.jpg
    - lib/Weapon/Images/sharp.jpg
    - lib/Weapon/Images/hotblaster.jpg
    - lib/Weapon/Images/dynamo.jpg
    - lib/Weapon/Images/hokusai.jpg
    - lib/Weapon/Images/splatscope.jpg
    - lib/Weapon/Images/bucketslosher.jpg
    - lib/Weapon/Images/barrelspinner.jpg
    - lib/Weapon/Images/sshooter_collabo.jpg
    - lib/Weapon/Images/wakaba.jpg
    - lib/Weapon/Images/sputtery.jpg
    - lib/Weapon/Images/clashblaster.jpg
    - lib/Weapon/Images/soytuber.jpg
    - lib/Weapon/Images/jetsweeper.jpg
    - lib/Weapon/Images/nzap85.jpg
    - lib/Weapon/Images/promodeler_rg.jpg
    - lib/Weapon/Images/promodeler_mg.jpg
    - lib/Weapon/Images/52gal.jpg
    - lib/Weapon/Images/96gal.jpg
    - lib/Weapon/Images/l3reelgun.jpg
    - lib/Weapon/Images/h3reelgun.jpg
    - lib/Weapon/Images/hotblaster_custom.jpg
    - lib/Weapon/Images/nova.jpg
    - lib/Weapon/Images/rapid.jpg
    - lib/Weapon/Images/maneuver_collabo.jpg
    - lib/Weapon/Images/splatroller_collabo.jpg
    - lib/Weapon/Images/variableroller.jpg
    - lib/Weapon/Images/carbon.jpg
    - lib/Weapon/Images/splatcharger_collabo.jpg
    - lib/Weapon/Images/splatscope_collabo.jpg
    - lib/Weapon/Images/liter4k.jpg
    - lib/Weapon/Images/liter4k_scope.jpg
    - lib/Weapon/Images/splatspinner.jpg
    - lib/Weapon/Images/hissen.jpg
    - lib/Weapon/Images/pablo.jpg
    - lib/Weapon/Images/dualsweeper.jpg
    - lib/Weapon/Images/bold.jpg
    - lib/Weapon/Images/heroshooter_replica.jpg
    - lib/Weapon/Images/heroblaster_replica.jpg
    - lib/Weapon/Images/heromaneuver_replica.jpg
    - lib/Weapon/Images/herocharger_replica.jpg
    - lib/Weapon/Images/heroroller_replica.jpg
    - lib/Weapon/Images/herobrush_replica.jpg
    - lib/Weapon/Images/heroslosher_replica.jpg
    - lib/Weapon/Images/herospinner_replica.jpg
    - lib/Weapon/Images/parashelter.jpg
    - lib/Weapon/Images/heroshelter_replica.jpg
    - lib/Weapon/Images/squiclean_a.jpg
    - lib/Weapon/Images/prime_collabo.jpg
    - lib/Weapon/Images/screwslosher.jpg
    - lib/Weapon/Images/momiji.jpg
    - lib/Weapon/Images/barrelspinner_deco.jpg
    - lib/Weapon/Images/rapid_elite.jpg
    - lib/Weapon/Images/campingshelter.jpg
    - lib/Weapon/Images/bamboo14mk1.jpg
    - lib/Weapon/Images/liter4k_custom.jpg
    - lib/Weapon/Images/liter4k_scope_custom.jpg
    - lib/Weapon/Images/longblaster.jpg
    - lib/Weapon/Images/dynamo_tesla.jpg
    - lib/Weapon/Images/jetsweeper_custom.jpg
    - lib/Weapon/Images/pablo_hue.jpg
    - lib/Weapon/Images/variableroller_foil.jpg
    - lib/Weapon/Images/hydra.jpg
    - lib/Weapon/Images/kelvin525.jpg
    - lib/Weapon/Images/nzap89.jpg
    - lib/Weapon/Images/bucketslosher_deco.jpg
    - lib/Weapon/Images/bottlegeyser.jpg
    - lib/Weapon/Images/spygadget.jpg
    - lib/Weapon/Images/hokusai_hue.jpg
    - lib/Weapon/Images/l3reelgun_d.jpg
    - lib/Weapon/Images/sputtery_hue.jpg
    - lib/Weapon/Images/52gal_deco.jpg
    - lib/Weapon/Images/rapid_deco.jpg
    - lib/Weapon/Images/96gal_deco.jpg
    - lib/Weapon/Images/soytuber_custom.jpg
    - lib/Weapon/Images/screwslosher_neo.jpg
    - lib/Weapon/Images/nova_neo.jpg
    - lib/Weapon/Images/quadhopper_black.jpg
    - lib/Weapon/Images/bold_neo.jpg
    - lib/Weapon/Images/h3reelgun_d.jpg
    - lib/Weapon/Images/splatspinner_collabo.jpg
    - lib/Weapon/Images/parashelter_sorella.jpg
    - lib/Weapon/Images/clashblaster_neo.jpg
    - lib/Weapon/Images/hissen_hue.jpg
    - lib/Weapon/Images/longblaster_custom.jpg
    - lib/Weapon/Images/sharp_neo.jpg
    - lib/Weapon/Images/bottlegeyser_foil.jpg
    - lib/Weapon/Images/squiclean_b.jpg
    - lib/Weapon/Images/kelvin525_deco.jpg
    - lib/Weapon/Images/dualsweeper_custom.jpg
    - lib/Weapon/Images/rapid_elite_deco.jpg
    - lib/Weapon/Images/spygadget_sorella.jpg
    - lib/Weapon/Images/carbon_deco.jpg
    - lib/Weapon/Images/octoshooter_replica.jpg
    - lib/Weapon/Images/bamboo14mk2.jpg
    - lib/Weapon/Images/campingshelter_sorella.jpg
    - lib/Weapon/Images/kugelschreiber.jpg
    - lib/Weapon/Images/explosher.jpg
    - lib/Weapon/Images/quadhopper_white.jpg
    - lib/Weapon/Images/hydra_custom.jpg
    - lib/Weapon/Images/furo.jpg
    - lib/Weapon/Images/nautilus47.jpg
    - lib/Weapon/Images/sshooter_becchu.jpg
    - lib/Weapon/Images/splatroller_becchu.jpg
    - lib/Weapon/Images/splatcharger_becchu.jpg
    - lib/Weapon/Images/splatscope_becchu.jpg
    - lib/Weapon/Images/maneuver_becchu.jpg
    - lib/Weapon/Images/prime_becchu.jpg
    - lib/Weapon/Images/nova_becchu.jpg
    - lib/Weapon/Images/dynamo_becchu.jpg
    - lib/Weapon/Images/screwslosher_becchu.jpg
    - lib/Weapon/Images/ochiba.jpg
    - lib/Weapon/Images/hokusai_becchu.jpg
    - lib/Weapon/Images/spygadget_becchu.jpg
    - lib/Weapon/Images/l3reelgun_becchu.jpg
    - lib/Weapon/Images/explosher_custom.jpg
    - lib/Weapon/Images/kugelschreiber_hue.jpg
    - lib/Weapon/Images/furo_deco.jpg
    - lib/Weapon/Images/nautilus79.jpg
    - lib/Weapon/Images/52gal_becchu.jpg
    - lib/Weapon/Images/kelvin525_becchu.jpg
    - lib/Weapon/Images/splatspinner_becchu.jpg
    - lib/Weapon/Images/rapid_becchu.jpg
    - lib/Weapon/Images/sputtery_clear.jpg
    - lib/Weapon/Images/campingshelter_camo.jpg
    - lib/Weapon/Images/squiclean_g.jpg
    - lib/Weapon/Images/pablo_permanent.jpg
    - lib/Weapon/Images/bucketslosher_soda.jpg
    - lib/Weapon/Images/barrelspinner_remix.jpg
    - lib/Weapon/Images/bamboo14mk3.jpg
    - lib/Weapon/Images/longblaster_necro.jpg
    - lib/Weapon/Images/nzap83.jpg
    - lib/Weapon/Images/promodeler_pg.jpg
    - lib/Weapon/Images/bold_7.jpg
    - lib/Weapon/Images/h3reelgun_cherry.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
